export const data = {
  results: [
    {
      name: 'Whiskers',
      age: 3,
      personality: ['playful', 'affectionate', 'curious'],
      img: 'https://placekitten.com/200/300',
      gender: 'Male',
      id: '7b2dfe5f-82b7-4a0b-a62e-69b5fd43d930',
      declawed: false,
      size: 'm',
      breed: 'Siamese',
    },
    {
      name: 'Fluffy',
      age: 5,
      personality: ['independent', 'curious', 'calm'],
      img: 'https://placekitten.com/250/350',
      gender: 'Female',
      id: 'e7b2b78a-7872-4f29-b1bf-08675009e52a',
      declawed: true,
      size: 'l',
      breed: 'Maine Coon',
    },
    {
      name: 'Mittens',
      age: 2,
      personality: ['energetic', 'friendly', 'outgoing'],
      img: 'https://placekitten.com/220/320',
      gender: 'Male',
      id: 'a5d4ccf5-513d-44b3-81a4-f2aa81d05f17',
      declawed: false,
      size: 's',
      breed: 'American Shorthair',
    },
    {
      name: 'Luna',
      age: 4,
      personality: ['calm', 'gentle', 'shy'],
      img: 'https://placekitten.com/240/340',
      gender: 'Female',
      id: 'de3cf46b-0f64-4045-95d7-98150c2858d9',
      declawed: true,
      size: 'm',
      breed: 'Scottish Fold',
    },
    {
      name: 'Oreo',
      age: 1,
      personality: ['mischievous', 'playful', 'spontaneous'],
      img: 'https://placekitten.com/230/330',
      gender: 'Male',
      id: 'a7e39f4d-7884-4b05-8957-f66f3626f55c',
      declawed: false,
      size: 's',
      breed: 'Ragdoll',
    },
    {
      name: 'Bella',
      age: 6,
      personality: ['cuddly', 'sweet', 'affectionate'],
      img: 'https://placekitten.com/260/360',
      gender: 'Female',
      id: '3cf089ff-5dd0-4659-bf71-6658b3db2637',
      declawed: true,
      size: 'l',
      breed: 'Persian',
    },
    {
      name: 'Simba',
      age: 2,
      personality: ['adventurous', 'playful', 'energetic'],
      img: 'https://placekitten.com/270/370',
      gender: 'Male',
      id: 'c15a0b6a-8fe6-4750-a192-0443095b4a02',
      declawed: false,
      size: 'm',
      breed: 'Bengal',
    },
    {
      name: 'Smokey',
      age: 3,
      personality: ['calm', 'observant', 'mysterious'],
      img: 'https://placekitten.com/280/380',
      gender: 'Male',
      id: '4296888b-eb86-41b4-9e38-cfa9ac73a5d2',
      declawed: true,
      size: 'm',
      breed: 'Russian Blue',
    },
    {
      name: 'Milo',
      age: 4,
      personality: ['friendly', 'loyal', 'gentle'],
      img: 'https://placekitten.com/290/390',
      gender: 'Male',
      id: '5338b8c0-f162-4349-a70f-72d95a49e6af',
      declawed: false,
      size: 'l',
      breed: 'Maine Coon',
    },
    {
      name: 'Chloe',
      age: 2,
      personality: ['independent', 'sassy', 'confident'],
      img: 'https://placekitten.com/300/400',
      gender: 'Female',
      id: 'ff9f170d-0a62-4e2c-a42a-61118d1f35b0',
      declawed: true,
      size: 'm',
      breed: 'Siamese',
    },
    {
      name: 'Shadow',
      age: 5,
      personality: ['mysterious', 'aloof', 'watchful'],
      img: 'https://placekitten.com/310/410',
      gender: 'Female',
      id: '3e5d2a6c-f6c8-4897-b255-0b3ad1604294',
      declawed: false,
      size: 'l',
      breed: 'Persian',
    },
    {
      name: 'Loki',
      age: 1,
      personality: ['mischievous', 'energetic', 'playful'],
      img: 'https://placekitten.com/320/420',
      gender: 'Male',
      id: 'c3f39d8b-2f75-4f17-867e-57d6d2729cc5',
      declawed: false,
      size: 's',
      breed: 'Sphynx',
    },
    {
      name: 'Cleo',
      age: 3,
      personality: ['affectionate', 'curious', 'gentle'],
      img: 'https://placekitten.com/330/430',
      gender: 'Female',
      id: 'f87c5a2a-70c4-4b32-80d6-03d9eaa2d6a9',
      declawed: true,
      size: 'm',
      breed: 'Ragdoll',
    },
    {
      name: 'Max',
      age: 2,
      personality: ['friendly', 'outgoing', 'energetic'],
      img: 'https://placekitten.com/340/440',
      gender: 'Male',
      id: '9b7db5f0-25bf-476d-9057-17cb19e2e234',
      declawed: false,
      size: 'm',
      breed: 'American Shorthair',
    },
    {
      name: 'Gizmo',
      age: 4,
      personality: ['quirky', 'inquisitive', 'sociable'],
      img: 'https://placekitten.com/350/450',
      gender: 'Male',
      id: '6b640cfd-90e4-4c46-9f42-30b0c8556d0f',
      declawed: true,
      size: 'l',
      breed: 'Birman',
    },
    {
      name: 'Mittens',
      age: 3,
      personality: ['calm', 'gentle', 'shy'],
      img: 'https://placekitten.com/360/460',
      gender: 'Female',
      id: '4e96b1e5-ec33-4762-a743-33ddac6efbf2',
      declawed: false,
      size: 'm',
      breed: 'Scottish Fold',
    },
    {
      name: 'Salem',
      age: 5,
      personality: ['mysterious', 'aloof', 'independent'],
      img: 'https://placekitten.com/370/470',
      gender: 'Male',
      id: 'b0a5f9d3-7e9c-4d71-8402-1ff1f56d11d3',
      declawed: true,
      size: 'm',
      breed: 'Bombay',
    },
    {
      name: 'Oliver',
      age: 2,
      personality: ['friendly', 'curious', 'playful'],
      img: 'https://placekitten.com/380/480',
      gender: 'Male',
      id: 'f14545c7-6b52-4b21-bc1f-6d85cf534066',
      declawed: false,
      size: 's',
      breed: 'Bengal',
    },
    {
      name: 'Sophie',
      age: 4,
      personality: ['sweet', 'affectionate', 'gentle'],
      img: 'https://placekitten.com/390/490',
      gender: 'Female',
      id: '1e8fbfc7-78e8-44fb-a3a1-96e2e1e373ab',
      declawed: true,
      size: 'm',
      breed: 'Persian',
    },
    {
      name: 'Leo',
      age: 3,
      personality: ['energetic', 'adventurous', 'playful'],
      img: 'https://placekitten.com/400/500',
      gender: 'Male',
      id: 'fc227c08-f562-46f5-9d9e-7d4e62b58550',
      declawed: false,
      size: 'm',
      breed: 'Maine Coon',
    },
    {
      name: 'Lily',
      age: 2,
      personality: ['loving', 'sociable', 'mischievous'],
      img: 'https://placekitten.com/410/510',
      gender: 'Female',
      id: '1ff1df16-d5d9-4629-b23f-8a6d98f9ef5b',
      declawed: false,
      size: 's',
      breed: 'Siamese',
    },
    {
      name: 'Milo',
      age: 4,
      personality: ['gentle', 'affectionate', 'curious'],
      img: 'https://placekitten.com/420/520',
      gender: 'Male',
      id: 'e35c69a6-5c51-4391-bf63-438a28b0e670',
      declawed: false,
      size: 'm',
      breed: 'Ragdoll',
    },
    {
      name: 'Olive',
      age: 3,
      personality: ['independent', 'playful', 'mischievous'],
      img: 'https://placekitten.com/430/530',
      gender: 'Female',
      id: '2dd4a276-f9b3-4da7-b79a-b3621005c7f7',
      declawed: true,
      size: 'm',
      breed: 'Siberian',
    },
    {
      name: 'Jack',
      age: 5,
      personality: ['friendly', 'outgoing', 'energetic'],
      img: 'https://placekitten.com/440/540',
      gender: 'Male',
      id: '4e5a42c2-f01f-4816-8c7b-6ebfc1c4eae2',
      declawed: true,
      size: 'l',
      breed: 'Scottish Fold',
    },
    {
      name: 'Mia',
      age: 2,
      personality: ['sweet', 'gentle', 'calm'],
      img: 'https://placekitten.com/450/550',
      gender: 'Female',
      id: '6ad048a4-bba2-4d10-af2a-ee6ab6d2b25d',
      declawed: false,
      size: 's',
      breed: 'Bengal',
    },
    {
      name: 'Charlie',
      age: 4,
      personality: ['curious', 'adventurous', 'playful'],
      img: 'https://placekitten.com/460/560',
      gender: 'Male',
      id: '55bb8b28-017d-41f1-80a0-8d0c0cbf1f84',
      declawed: false,
      size: 'm',
      breed: 'Maine Coon',
    },
    {
      name: 'Lucy',
      age: 3,
      personality: ['loving', 'sociable', 'friendly'],
      img: 'https://placekitten.com/470/570',
      gender: 'Female',
      id: 'b2c53cf5-51c4-479b-8b4e-83994c7d464d',
      declawed: false,
      size: 'm',
      breed: 'Siamese',
    },
    {
      name: 'Tiger',
      age: 4,
      personality: ['independent', 'curious', 'adventurous'],
      img: 'https://placekitten.com/480/580',
      gender: 'Male',
      id: '3f78f045-9b14-4788-b4c4-46e3ef6f6cf7',
      declawed: true,
      size: 'l',
      breed: 'Bengal',
    },
    {
      name: 'Sophie',
      age: 2,
      personality: ['gentle', 'calm', 'sweet'],
      img: 'https://placekitten.com/490/590',
      gender: 'Female',
      id: 'fc8790a7-5e3d-4f3f-8971-c398a009f7c2',
      declawed: false,
      size: 's',
      breed: 'Scottish Fold',
    },
    {
      name: 'Leo',
      age: 5,
      personality: ['playful', 'energetic', 'friendly'],
      img: 'https://placekitten.com/500/600',
      gender: 'Male',
      id: '048bf540-04f3-4665-8e50-33ee8cde4e09',
      declawed: false,
      size: 'm',
      breed: 'Siberian',
    },
    {
      name: 'Luna',
      age: 3,
      personality: ['affectionate', 'playful', 'loving'],
      img: 'https://placekitten.com/510/610',
      gender: 'Female',
      id: 'bc94d54d-612d-4296-8506-1b1285b98c39',
      declawed: false,
      size: 'm',
      breed: 'Maine Coon',
    },
    {
      name: 'Max',
      age: 4,
      personality: ['friendly', 'gentle', 'calm'],
      img: 'https://placekitten.com/520/620',
      gender: 'Male',
      id: 'bc6d98a1-1569-4b1c-bcd7-89484a9a1f0a',
      declawed: false,
      size: 'm',
      breed: 'Persian',
    },
    {
      name: 'Ziggy',
      age: 3,
      personality: ['playful', 'curious', 'energetic'],
      img: 'https://placekitten.com/530/630',
      gender: 'Male',
      id: 'bc6d98a1-1569-4b1c-bcd7-89484a9a1f0a',
      declawed: false,
      size: 'm',
      breed: 'American Shorthair',
    },
    {
      name: 'Lily',
      age: 2,
      personality: ['loving', 'sociable', 'gentle'],
      img: 'https://placekitten.com/540/640',
      gender: 'Female',
      id: '50b240a6-b0c4-4f7f-8b43-c487a4d84b53',
      declawed: true,
      size: 's',
      breed: 'Ragdoll',
    },
    {
      name: 'Simba',
      age: 5,
      personality: ['playful', 'affectionate', 'curious'],
      img: 'https://placekitten.com/550/650',
      gender: 'Male',
      id: 'f27b5318-1f3e-4d63-a944-ef271c91cd5b',
      declawed: true,
      size: 'l',
      breed: 'Siamese',
    },
    {
      name: 'Misty',
      age: 4,
      personality: ['independent', 'calm', 'mysterious'],
      img: 'https://placekitten.com/560/660',
      gender: 'Female',
      id: 'e5a5758a-893d-4705-8891-1c7c83718f1e',
      declawed: false,
      size: 'm',
      breed: 'Scottish Fold',
    },
    {
      name: 'Milo',
      age: 3,
      personality: ['energetic', 'playful', 'friendly'],
      img: 'https://placekitten.com/570/670',
      gender: 'Male',
      id: 'b1681d13-c54d-4626-b71f-65448d5e4860',
      declawed: false,
      size: 'm',
      breed: 'Maine Coon',
    },
    {
      name: 'Bella',
      age: 2,
      personality: ['affectionate', 'curious', 'gentle'],
      img: 'https://placekitten.com/580/680',
      gender: 'Female',
      id: '727b1712-494d-4936-87d5-d6d65b4bdf32',
      declawed: true,
      size: 's',
      breed: 'Persian',
    },
    {
      name: 'Charlie',
      age: 4,
      personality: ['friendly', 'outgoing', 'loyal'],
      img: 'https://placekitten.com/590/690',
      gender: 'Male',
      id: '61735fe7-5fa6-4a06-8328-d3b19649b7bf',
      declawed: false,
      size: 'l',
      breed: 'Siberian',
    },
    {
      name: 'Luna',
      age: 3,
      personality: ['playful', 'energetic', 'mischievous'],
      img: 'https://placekitten.com/600/700',
      gender: 'Female',
      id: '2adaf3fb-1cfd-4a43-9a2d-5164c6d4e962',
      declawed: false,
      size: 'm',
      breed: 'Bengal',
    },
    {
      name: 'Max',
      age: 5,
      personality: ['gentle', 'sweet', 'calm'],
      img: 'https://placekitten.com/610/710',
      gender: 'Male',
      id: '09f48e50-1718-4e85-a1e6-6a9a82b7dc15',
      declawed: false,
      size: 'm',
      breed: 'American Shorthair',
    },
    {
      name: 'Oliver',
      age: 4,
      personality: ['curious', 'playful', 'energetic'],
      img: 'https://placekitten.com/620/720',
      gender: 'Male',
      id: '3d47f0d2-31c3-4316-9f32-2f56c24a5e6a',
      declawed: false,
      size: 'm',
      breed: 'Maine Coon',
    },
    {
      name: 'Sophie',
      age: 3,
      personality: ['affectionate', 'gentle', 'loving'],
      img: 'https://placekitten.com/630/730',
      gender: 'Female',
      id: 'c056c32f-9d59-4c6c-ae2e-b2f4380181ae',
      declawed: false,
      size: 'm',
      breed: 'Ragdoll',
    },
    {
      name: 'Simba',
      age: 2,
      personality: ['adventurous', 'brave', 'loyal'],
      img: 'https://placekitten.com/640/740',
      gender: 'Male',
      id: 'aaf3e62f-4b42-47c5-b8bc-0b48f55ddc9d',
      declawed: true,
      size: 'l',
      breed: 'Siamese',
    },
    {
      name: 'Luna',
      age: 5,
      personality: ['cuddly', 'sweet', 'gentle'],
      img: 'https://placekitten.com/650/750',
      gender: 'Female',
      id: '8db81c22-79f8-4217-94f1-7758b9b60ee3',
      declawed: false,
      size: 'm',
      breed: 'Scottish Fold',
    },
    {
      name: 'Tiger',
      age: 3,
      personality: ['playful', 'energetic', 'friendly'],
      img: 'https://placekitten.com/660/760',
      gender: 'Male',
      id: '50f8807d-eb25-476f-aae8-5d2d858ac0fc',
      declawed: false,
      size: 'm',
      breed: 'Bengal',
    },
    {
      name: 'Milo',
      age: 4,
      personality: ['gentle', 'affectionate', 'friendly'],
      img: 'https://placekitten.com/670/770',
      gender: 'Male',
      id: '3c82441a-35b7-4ff2-a97e-217ac30d7d3b',
      declawed: false,
      size: 'm',
      breed: 'Persian',
    },
    {
      name: 'Luna',
      age: 3,
      personality: ['playful', 'energetic', 'mischievous'],
      img: 'https://placekitten.com/680/780',
      gender: 'Female',
      id: '77d59e8f-b9e4-4f80-9b5f-41ae13cb64cd',
      declawed: false,
      size: 'm',
      breed: 'American Shorthair',
    },
    {
      name: 'Leo',
      age: 2,
      personality: ['curious', 'playful', 'energetic'],
      img: 'https://placekitten.com/690/790',
      gender: 'Male',
      id: '24b49e08-6f29-405d-9820-59a83174a497',
      declawed: false,
      size: 'm',
      breed: 'Siberian',
    },
    {
      name: 'Mia',
      age: 5,
      personality: ['gentle', 'sweet', 'calm'],
      img: 'https://placekitten.com/700/800',
      gender: 'Female',
      id: '9b86c9d1-3bdf-4e80-af8e-d60d3b1aa0f7',
      declawed: false,
      size: 'm',
      breed: 'Maine Coon',
    },
    {
      name: 'Charlie',
      age: 4,
      personality: ['friendly', 'outgoing', 'loyal'],
      img: 'https://placekitten.com/710/810',
      gender: 'Male',
      id: '44d5c364-11a5-441a-ba21-1ac3922a6e0c',
      declawed: false,
      size: 'm',
      breed: 'Ragdoll',
    },
    {
      name: 'Sasha',
      age: 3,
      personality: ['energetic', 'playful', 'friendly'],
      img: 'https://placekitten.com/720/820',
      gender: 'Female',
      id: 'f302ff0c-1da9-4e3a-91a4-00b1711c2058',
      declawed: false,
      size: 'm',
      breed: 'Bengal',
    },
    {
      name: 'Toby',
      age: 4,
      personality: ['curious', 'adventurous', 'brave'],
      img: 'https://placekitten.com/730/830',
      gender: 'Male',
      id: 'aa23dc4e-2035-4182-a0e4-356a072fe9bf',
      declawed: false,
      size: 'm',
      breed: 'Maine Coon',
    },
    {
      name: 'Lola',
      age: 2,
      personality: ['sweet', 'gentle', 'loving'],
      img: 'https://placekitten.com/740/840',
      gender: 'Female',
      id: '68c2358b-8b05-40e8-9715-4d4e79a4bfe8',
      declawed: false,
      size: 's',
      breed: 'Scottish Fold',
    },
    {
      name: 'Rocky',
      age: 5,
      personality: ['calm', 'mellow', 'loyal'],
      img: 'https://placekitten.com/750/850',
      gender: 'Male',
      id: 'b4f425d5-2b6d-47b8-bb71-82b3834a6a7a',
      declawed: false,
      size: 'm',
      breed: 'Persian',
    },
    {
      name: 'Nala',
      age: 3,
      personality: ['playful', 'sassy', 'energetic'],
      img: 'https://placekitten.com/760/860',
      gender: 'Female',
      id: 'ef9f7560-1e6f-4575-ae4e-39d8f92419a5',
      declawed: true,
      size: 'm',
      breed: 'Siamese',
    },
    {
      name: 'Mochi',
      age: 4,
      personality: ['calm', 'gentle', 'sweet'],
      img: 'https://placekitten.com/770/870',
      gender: 'Male',
      id: 'c388aadd-3b78-4e4b-8a44-d94f8a7b9864',
      declawed: false,
      size: 'm',
      breed: 'Ragdoll',
    },
    {
      name: 'Zoe',
      age: 3,
      personality: ['friendly', 'outgoing', 'energetic'],
      img: 'https://placekitten.com/780/880',
      gender: 'Female',
      id: '21ad9b85-d657-4a9d-9fc0-764556e7f454',
      declawed: false,
      size: 'm',
      breed: 'Bengal',
    },
    {
      name: 'Gus',
      age: 2,
      personality: ['playful', 'energetic', 'mischievous'],
      img: 'https://placekitten.com/790/890',
      gender: 'Male',
      id: 'c86112f6-bc5f-4aee-b1ee-4e96de9e40aa',
      declawed: false,
      size: 's',
      breed: 'Scottish Fold',
    },
    {
      name: 'Luna',
      age: 5,
      personality: ['gentle', 'loving', 'affectionate'],
      img: 'https://placekitten.com/800/900',
      gender: 'Female',
      id: 'e17b43e3-8b77-47ee-91c5-bcbb17c78f8d',
      declawed: true,
      size: 'm',
      breed: 'Persian',
    },
    {
      name: 'Finn',
      age: 3,
      personality: ['friendly', 'outgoing', 'loyal'],
      img: 'https://placekitten.com/810/910',
      gender: 'Male',
      id: 'b975314d-fd75-4a49-b89f-4a38c803b914',
      declawed: false,
      size: 'm',
      breed: 'Maine Coon',
    },
    {
      name: 'Mochi',
      age: 4,
      personality: ['calm', 'gentle', 'sweet'],
      img: 'https://placekitten.com/770/870',
      gender: 'Male',
      id: 'c388aadd-3b78-4e4b-8a44-d94f8a7b9864',
      declawed: false,
      size: 'm',
      breed: 'British Shorthair',
    },
    {
      name: 'Zoe',
      age: 3,
      personality: ['friendly', 'outgoing', 'energetic'],
      img: 'https://placekitten.com/780/880',
      gender: 'Female',
      id: '21ad9b85-d657-4a9d-9fc0-764556e7f454',
      declawed: false,
      size: 'm',
      breed: 'Siamese',
    },
    {
      name: 'Gus',
      age: 2,
      personality: ['playful', 'energetic', 'mischievous'],
      img: 'https://placekitten.com/790/890',
      gender: 'Male',
      id: 'c86112f6-bc5f-4aee-b1ee-4e96de9e40aa',
      declawed: false,
      size: 's',
      breed: 'Birman',
    },
    {
      name: 'Luna',
      age: 5,
      personality: ['gentle', 'loving', 'affectionate'],
      img: 'https://placekitten.com/800/900',
      gender: 'Female',
      id: 'e17b43e3-8b77-47ee-91c5-bcbb17c78f8d',
      declawed: true,
      size: 'm',
      breed: 'Burmese',
    },
    {
      name: 'Finn',
      age: 3,
      personality: ['friendly', 'outgoing', 'loyal'],
      img: 'https://placekitten.com/810/910',
      gender: 'Male',
      id: 'b975314d-fd75-4a49-b89f-4a38c803b914',
      declawed: false,
      size: 'm',
      breed: 'Himalayan',
    },
    {
      name: 'Whiskers',
      age: 6,
      personality: ['calm', 'gentle', 'independent'],
      img: 'https://placekitten.com/820/920',
      gender: 'Male',
      id: '5e464497-63b3-41f0-8c41-844650e32d98',
      declawed: false,
      size: 'm',
      breed: 'Russian Blue',
    },
    {
      name: 'Mittens',
      age: 7,
      personality: ['affectionate', 'sociable', 'relaxed'],
      img: 'https://placekitten.com/830/930',
      gender: 'Female',
      id: '21ad9b85-d657-4a9d-9fc0-764556e7f454',
      declawed: false,
      size: 'm',
      breed: 'Sphynx',
    },
    {
      name: 'Shadow',
      age: 8,
      personality: ['mysterious', 'independent', 'observant'],
      img: 'https://placekitten.com/840/940',
      gender: 'Male',
      id: 'c86112f6-bc5f-4aee-b1ee-4e96de9e40aa',
      declawed: false,
      size: 's',
      breed: 'Devon Rex',
    },
    {
      name: 'Smokey',
      age: 9,
      personality: ['wise', 'loyal', 'gentle'],
      img: 'https://placekitten.com/850/950',
      gender: 'Male',
      id: 'e17b43e3-8b77-47ee-91c5-bcbb17c78f8d',
      declawed: true,
      size: 'm',
      breed: 'Norwegian Forest Cat',
    },
    {
      name: 'Midnight',
      age: 10,
      personality: ['calm', 'wise', 'relaxed'],
      img: 'https://placekitten.com/860/960',
      gender: 'Female',
      id: 'b975314d-fd75-4a49-b89f-4a38c803b914',
      declawed: false,
      size: 'm',
      breed: 'British Longhair',
    },
    {
      name: 'Cleo',
      age: 11,
      personality: ['sassy', 'independent', 'observant'],
      img: 'https://placekitten.com/870/970',
      gender: 'Female',
      id: '29a44f9a-8476-4347-b3f6-895fbb9f7e9e',
      declawed: false,
      size: 'm',
      breed: 'Bombay',
    },
    {
      name: 'Oreo',
      age: 12,
      personality: ['gentle', 'friendly', 'wise'],
      img: 'https://placekitten.com/880/980',
      gender: 'Male',
      id: 'e081b5dc-d18c-443b-8760-b19808fe7f1e',
      declawed: false,
      size: 'm',
      breed: 'Cornish Rex',
    },
    {
      name: 'Salem',
      age: 13,
      personality: ['mysterious', 'calm', 'independent'],
      img: 'https://placekitten.com/890/990',
      gender: 'Male',
      id: '27648b8f-8623-4b6b-a9ef-8b1d75c5355c',
      declawed: false,
      size: 's',
      breed: 'Turkish Angora',
    },
    {
      name: 'Casper',
      age: 14,
      personality: ['gentle', 'calm', 'wise'],
      img: 'https://placekitten.com/900/1000',
      gender: 'Male',
      id: '2f615c95-77e7-4c77-a2cb-f9db83ab1a02',
      declawed: false,
      size: 'm',
      breed: 'American Bobtail',
    },
    {
      name: 'Misty',
      age: 15,
      personality: ['sweet', 'loving', 'gentle'],
      img: 'https://placekitten.com/910/1010',
      gender: 'Female',
      id: '0df8db3e-095d-4d06-8db9-6162a7ad7fd9',
      declawed: true,
      size: 'm',
      breed: 'Havana Brown',
    },
    {
      name: 'Shadow',
      age: 16,
      personality: ['mysterious', 'calm', 'independent'],
      img: 'https://placekitten.com/920/1020',
      gender: 'Male',
      id: '6a75b122-28de-4e61-b3fc-c6a2c2edde8c',
      declawed: false,
      size: 'm',
      breed: 'Japanese Bobtail',
    },
    {
      name: 'Angel',
      age: 17,
      personality: ['sweet', 'gentle', 'loving'],
      img: 'https://placekitten.com/930/1030',
      gender: 'Female',
      id: '5f2bb0f2-8b18-4a89-a7d4-7c0f0b146d46',
      declawed: false,
      size: 'm',
      breed: 'Manx',
    },
    {
      name: 'Mittens',
      age: 18,
      personality: ['friendly', 'outgoing', 'energetic'],
      img: 'https://placekitten.com/940/1040',
      gender: 'Male',
      id: '6a43d22e-731f-4d82-bba4-17835c175446',
      declawed: false,
      size: 'm',
      breed: 'Turkish Van',
    },
    {
      name: 'Smokey',
      age: 19,
      personality: ['calm', 'gentle', 'wise'],
      img: 'https://placekitten.com/950/1050',
      gender: 'Male',
      id: '32c4c2d4-348a-490a-8e6f-940d6bf92e46',
      declawed: false,
      size: 'm',
      breed: 'Oriental',
    },
    {
      name: 'Cleo',
      age: 20,
      personality: ['sassy', 'independent', 'observant'],
      img: 'https://placekitten.com/960/1060',
      gender: 'Female',
      id: 'c157b310-dc2b-4d80-bc5a-5c4bb4b4c961',
      declawed: false,
      size: 'm',
      breed: 'Pixiebob',
    },
    {
      name: 'Sylvester',
      age: 21,
      personality: ['mysterious', 'independent', 'calm'],
      img: 'https://placekitten.com/970/1070',
      gender: 'Male',
      id: '785238a3-2017-4872-88f7-5e8f9d2a1b2c',
      declawed: false,
      size: 'm',
      breed: 'American Wirehair',
    },
    {
      name: 'Misty',
      age: 22,
      personality: ['gentle', 'calm', 'wise'],
      img: 'https://placekitten.com/980/1080',
      gender: 'Female',
      id: '8579e1b5-22e7-4d6a-b00b-7c10aa37c746',
      declawed: false,
      size: 'm',
      breed: 'Burmilla',
    },
    {
      name: 'Max',
      age: 23,
      personality: ['friendly', 'loyal', 'energetic'],
      img: 'https://placekitten.com/990/1090',
      gender: 'Male',
      id: '1b92633d-540a-4e57-9267-8e1098d8dc5a',
      declawed: false,
      size: 'm',
      breed: 'Egyptian Mau',
    },
    {
      name: 'Cinder',
      age: 24,
      personality: ['sweet', 'affectionate', 'gentle'],
      img: 'https://placekitten.com/1000/1100',
      gender: 'Female',
      id: 'a7f4b019-c9eb-4b2d-b15f-c17708b17448',
      declawed: false,
      size: 'm',
      breed: 'Korat',
    },
    {
      name: 'Rocky',
      age: 25,
      personality: ['brave', 'playful', 'energetic'],
      img: 'https://placekitten.com/1010/1110',
      gender: 'Male',
      id: '1e57ccf6-3b8b-4745-b5a3-22fb6dc8f5b0',
      declawed: false,
      size: 'm',
      breed: 'American Curl',
    },
    {
      name: 'Whiskers',
      age: 26,
      personality: ['wise', 'calm', 'gentle'],
      img: 'https://placekitten.com/1020/1120',
      gender: 'Male',
      id: 'a140f245-16da-4ef3-96a8-efad1f8e7c8c',
      declawed: false,
      size: 'm',
      breed: 'Bengal',
    },
    {
      name: 'Willow',
      age: 27,
      personality: ['friendly', 'affectionate', 'playful'],
      img: 'https://placekitten.com/1030/1130',
      gender: 'Female',
      id: 'cd3ee100-e30a-4d78-a36c-6d12916812f6',
      declawed: false,
      size: 'm',
      breed: 'Chartreux',
    },
    {
      name: 'Mittens',
      age: 28,
      personality: ['loyal', 'brave', 'adventurous'],
      img: 'https://placekitten.com/1040/1140',
      gender: 'Male',
      id: 'd96ee04f-015a-499d-b0d8-d31d91c896ef',
      declawed: false,
      size: 'm',
      breed: 'Havana Brown',
    },
    {
      name: 'Luna',
      age: 29,
      personality: ['energetic', 'playful', 'curious'],
      img: 'https://placekitten.com/1050/1150',
      gender: 'Female',
      id: 'a4bb8a7c-c792-4673-819b-7e2931580137',
      declawed: false,
      size: 'm',
      breed: 'Munchkin',
    },
    {
      name: 'Oscar',
      age: 30,
      personality: ['calm', 'gentle', 'affectionate'],
      img: 'https://placekitten.com/1060/1160',
      gender: 'Male',
      id: 'b20f6c08-7c24-4ef6-9e5c-d2188aaf4b4b',
      declawed: false,
      size: 'm',
      breed: 'Russian Blue',
    },
    {
      name: 'Loki',
      age: 6,
      personality: ['mischievous', 'playful', 'energetic'],
      img: 'https://placekitten.com/1070/1170',
      gender: 'Male',
      id: 'cc06f0ef-32a3-4b82-8f59-b4641d74db25',
      declawed: false,
      size: 'm',
      breed: 'Siberian',
    },
    {
      name: 'Misto',
      age: 7,
      personality: ['gentle', 'affectionate', 'loving'],
      img: 'https://placekitten.com/1080/1180',
      gender: 'Female',
      id: '5b79c8b2-3a78-44fd-aa8c-c0a894c10710',
      declawed: false,
      size: 'm',
      breed: 'Ragamuffin',
    },
    {
      name: 'Socks',
      age: 8,
      personality: ['friendly', 'outgoing', 'social'],
      img: 'https://placekitten.com/1090/1190',
      gender: 'Male',
      id: '0b69f38a-6f86-4f7e-9c11-b01962b44625',
      declawed: false,
      size: 'm',
      breed: 'Tonkinese',
    },
    {
      name: 'Misteeze',
      age: 9,
      personality: ['calm', 'gentle', 'wise'],
      img: 'https://placekitten.com/1100/1200',
      gender: 'Female',
      id: '99af392e-8a24-42a3-801f-98b3af94341b',
      declawed: false,
      size: 'm',
      breed: 'Balinese',
    },
    {
      name: 'Felix',
      age: 5,
      personality: ['adventurous', 'brave', 'curious'],
      img: 'https://placekitten.com/1110/1210',
      gender: 'Male',
      id: '48aa78cf-0143-4749-bd0a-74b420e80297',
      declawed: false,
      size: 'm',
      breed: 'Sphynx',
    },
    {
      name: 'Milo',
      age: 7,
      personality: ['friendly', 'loyal', 'affectionate'],
      img: 'https://placekitten.com/1120/1220',
      gender: 'Male',
      id: '1b67de03-68b5-4a13-af90-9a44037d6c7a',
      declawed: false,
      size: 'm',
      breed: 'Scottish Fold',
    },
    {
      name: 'Bella',
      age: 8,
      personality: ['playful', 'energetic', 'curious'],
      img: 'https://placekitten.com/1130/1230',
      gender: 'Female',
      id: 'c67d25d7-3ee2-4b3f-af3d-d9493db4dc02',
      declawed: false,
      size: 'm',
      breed: 'Bengal',
    },
    {
      name: 'Oliver',
      age: 9,
      personality: ['mischievous', 'playful', 'energetic'],
      img: 'https://placekitten.com/1140/1240',
      gender: 'Male',
      id: 'b192f066-0c0b-4b18-b2b2-218ef2c99e02',
      declawed: false,
      size: 'm',
      breed: 'Ragdoll',
    },
    {
      name: 'Luna',
      age: 6,
      personality: ['gentle', 'loving', 'affectionate'],
      img: 'https://placekitten.com/1150/1250',
      gender: 'Female',
      id: '0d1242d3-d16b-4edf-b1b3-7c486408d609',
      declawed: true,
      size: 'm',
      breed: 'Siamese',
    },
  ],
  total: 100,
};
